### ISSUE TITLE
Unable to download individuals

### ISSUE THREAD

**Issue by bcbane** [Linekio/getmyancestors#10]
I get the following error when I try to download 6 generations

Login to FamilySearch...
Download starting individuals...
Traceback (most recent call last):
  File "getmyancestors.py", line 933, in <module>
    tree.add_indis(todo)
  File "getmyancestors.py", line 743, in add_indis
    loop.run_until_complete(add_datas(loop, data))
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "getmyancestors.py", line 730, in add_datas
    await future
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "getmyancestors.py", line 511, in add_data
    self.memories.add(Memorie(x))
  File "getmyancestors.py", line 364, in __init__
    self.url = data['links']['alternate'][0]['href']
KeyError: 'alternate'

**Comment by Linekio** [comment]
Make sure you use the latest version. If the problem persists, please provide me the log file.

**Comment by Linekio** [comment]
I close this issue because no response for 1 month, and I think it's a bug previously fixed by 828c8d096bfaff56f238fc1607e0671ab231c78b
