### ISSUE TITLE
GUI hangs on Exception

### ISSUE THREAD

**Issue by nextgeninternet** [Linekio/getmyancestors#29]
When attempting to download ID "LHB1-8MV"  1 generations ascend and 1 generations descend, add spouses and couples and temple info the GUI application hangs.

[download.log](https://github.com/Linekio/getmyancestors/files/4226660/download.log)

  **Console Output**

`[2020-02-19 12:16:00]: Downloading: /platform/tree/persons/LH1M-M2X/notes.json
[2020-02-19 12:16:01]: Status code: 200
[2020-02-19 12:16:01]: Downloading: /platform/tree/persons/KZ9C-6ZP/notes.json
[2020-02-19 12:16:01]: Status code: 200
[2020-02-19 12:16:01]: Downloading: /service/tree/tree-data/reservations/person/
KZ9C-6ZP/ordinances
[2020-02-19 12:16:01]: Status code: 204
[2020-02-19 12:16:01]: Downloading: /platform/tree/persons/LHB1-Q2R/notes.json
[2020-02-19 12:16:01]: Status code: 200
[2020-02-19 12:16:01]: Downloading: /service/tree/tree-data/reservations/person/
LHB1-Q2R/ordinances
[2020-02-19 12:16:02]: Status code: 204
[2020-02-19 12:16:02]: Downloading: /platform/tree/persons/LB3Y-LCL/notes.json
[2020-02-19 12:16:02]: Status code: 204
[2020-02-19 12:16:02]: Downloading: /service/tree/tree-data/reservations/person/
LB3Y-LCL/ordinances
[2020-02-19 12:16:02]: Status code: 204
[2020-02-19 12:16:02]: Status code: 200
[2020-02-19 12:16:02]: Downloading: /platform/tree/persons/KC2C-9V2/notes.json
[2020-02-19 12:16:02]: Downloading: /service/tree/tree-data/reservations/person/
KC2C-9V2/ordinances
[2020-02-19 12:16:03]: Status code: 200
[2020-02-19 12:16:03]: Downloading: /platform/tree/persons/LK3K-MWR/notes.json
[2020-02-19 12:16:03]: Status code: 200
[2020-02-19 12:16:03]: Downloading: /service/tree/tree-data/reservations/person/
LK3K-MWR/ordinances
[2020-02-19 12:16:03]: Status code: 204
[2020-02-19 12:16:03]: Downloading: /platform/tree/persons/LH1M-M6W/notes.json
[2020-02-19 12:16:03]: Status code: 200
[2020-02-19 12:16:03]: Downloading: /service/tree/tree-data/reservations/person/
LH1M-M6W/ordinances
[2020-02-19 12:16:04]: Status code: 200
[2020-02-19 12:16:04]: Downloading: /platform/tree/persons/KZ51-1LS/notes.json
[2020-02-19 12:16:04]: Status code: 204
[2020-02-19 12:16:04]: Status code: 200
[2020-02-19 12:16:04]: Downloading: /service/tree/tree-data/reservations/person/
KZ51-1LS/ordinances
[2020-02-19 12:16:04]: Downloading: /platform/tree/persons/LB3Y-LTC/notes.json
[2020-02-19 12:16:04]: Status code: 200
[2020-02-19 12:16:04]: Downloading: /service/tree/tree-data/reservations/person/
LB3Y-LTC/ordinances
[2020-02-19 12:16:04]: Status code: 200
[2020-02-19 12:16:04]: Downloading: /platform/tree/persons/LH5L-P7P/notes.json
[2020-02-19 12:16:04]: Status code: 204
[2020-02-19 12:16:04]: Downloading: /service/tree/tree-data/reservations/person/
LH5L-P7P/ordinances
[2020-02-19 12:16:05]: Status code: 200
[2020-02-19 12:16:05]: Downloading: /platform/tree/persons/LZFC-5KZ/notes.json
[2020-02-19 12:16:05]: Status code: 204
[2020-02-19 12:16:05]: Downloading: /service/tree/tree-data/reservations/person/
LZFC-5KZ/ordinances
[2020-02-19 12:16:05]: Status code: 200
[2020-02-19 12:16:05]: Downloading: /platform/tree/persons/K8N9-YFL/notes.json
[2020-02-19 12:16:05]: Status code: 204
[2020-02-19 12:16:05]: Downloading: /service/tree/tree-data/reservations/person/
K8N9-YFL/ordinances
[2020-02-19 12:16:05]: Status code: 200
[2020-02-19 12:16:05]: Downloading: /platform/tree/persons/KCBD-DW5/notes.json
[2020-02-19 12:16:05]: Status code: 200
[2020-02-19 12:16:05]: Downloading: /service/tree/tree-data/reservations/person/
KCBD-DW5/ordinances
[2020-02-19 12:16:06]: Status code: 204
[2020-02-19 12:16:06]: Downloading: /platform/tree/persons/MRHD-X56/notes.json
[2020-02-19 12:16:06]: Status code: 200
[2020-02-19 12:16:06]: Status code: 204
[2020-02-19 12:16:06]: Downloading: /service/tree/tree-data/reservations/person/
MRHD-X56/ordinances
[2020-02-19 12:16:06]: Status code: 200
[2020-02-19 12:16:06]: Downloading: /platform/tree/persons/MQ56-DS2/notes.json
[2020-02-19 12:16:06]: Downloading: /service/tree/tree-data/reservations/person/
MQ56-DS2/ordinances
[2020-02-19 12:16:06]: Status code: 204
[2020-02-19 12:16:06]: Downloading: /platform/tree/persons/LZ85-KSZ/notes.json
[2020-02-19 12:16:06]: Status code: 200
[2020-02-19 12:16:06]: Downloading: /service/tree/tree-data/reservations/person/
LZ85-KSZ/ordinances
[2020-02-19 12:16:08]: Status code: 204
[2020-02-19 12:16:08]: Downloading: /platform/tree/persons/KHXG-4SN/notes.json
[2020-02-19 12:16:08]: Status code: 200
[2020-02-19 12:16:08]: Status code: 204
[2020-02-19 12:16:08]: Downloading: /service/tree/tree-data/reservations/person/
KHXG-4SN/ordinances
[2020-02-19 12:16:08]: Downloading: /platform/tree/persons/K85L-7K6/notes.json
[2020-02-19 12:16:08]: Status code: 200
[2020-02-19 12:16:08]: Status code: 204
[2020-02-19 12:16:08]: Downloading: /service/tree/tree-data/reservations/person/
K85L-7K6/ordinances
[2020-02-19 12:16:08]: Downloading: /platform/tree/persons/L6VN-5KY/notes.json
[2020-02-19 12:16:08]: Status code: 200
[2020-02-19 12:16:08]: Downloading: /service/tree/tree-data/reservations/person/
L6VN-5KY/ordinances
[2020-02-19 12:16:09]: Status code: 200
[2020-02-19 12:16:09]: Downloading: /platform/tree/persons/LHB1-X7R/notes.json
[2020-02-19 12:16:09]: Status code: 204
[2020-02-19 12:16:09]: Downloading: /service/tree/tree-data/reservations/person/
LHB1-X7R/ordinances
[2020-02-19 12:16:09]: Status code: 204
[2020-02-19 12:16:09]: Downloading: /platform/tree/persons/KZ7Z-TRM/notes.json
[2020-02-19 12:16:09]: Status code: 204
[2020-02-19 12:16:09]: Downloading: /service/tree/tree-data/reservations/person/
KZ7Z-TRM/ordinances
[2020-02-19 12:16:09]: Status code: 200
[2020-02-19 12:16:09]: Downloading: /platform/tree/persons/MB8K-TCV/notes.json
[2020-02-19 12:16:09]: Status code: 200
[2020-02-19 12:16:09]: Downloading: /service/tree/tree-data/reservations/person/
MB8K-TCV/ordinances
[2020-02-19 12:16:10]: Status code: 204
[2020-02-19 12:16:10]: Downloading: /platform/tree/persons/LHB5-Z49/notes.json
[2020-02-19 12:16:10]: Status code: 200
[2020-02-19 12:16:10]: Downloading: /service/tree/tree-data/reservations/person/
LHB5-Z49/ordinances
[2020-02-19 12:16:10]: Status code: 200
[2020-02-19 12:16:10]: Downloading: /platform/tree/persons/MB8K-GQ6/notes.json
[2020-02-19 12:16:10]: Status code: 200
[2020-02-19 12:16:10]: Downloading: /service/tree/tree-data/reservations/person/
MB8K-GQ6/ordinances
[2020-02-19 12:16:10]: Status code: 204
[2020-02-19 12:16:10]: Downloading: /platform/tree/persons/LHB1-C4R/notes.json
[2020-02-19 12:16:11]: Status code: 200
[2020-02-19 12:16:11]: Downloading: /service/tree/tree-data/reservations/person/
LHB1-C4R/ordinances
[2020-02-19 12:16:11]: Status code: 204
[2020-02-19 12:16:11]: Status code: 204
[2020-02-19 12:16:11]: Status code: 200
[2020-02-19 12:16:11]: Downloading: /platform/tree/persons/LB3Y-5SW/notes.json
[2020-02-19 12:16:11]: Downloading: /service/tree/tree-data/reservations/person/
LB3Y-5SW/ordinances
[2020-02-19 12:16:11]: Downloading: /platform/tree/persons/2S3G-RMZ/notes.json
[2020-02-19 12:16:11]: Status code: 204
[2020-02-19 12:16:11]: Downloading: /service/tree/tree-data/reservations/person/
2S3G-RMZ/ordinances
[2020-02-19 12:16:11]: Status code: 200
[2020-02-19 12:16:12]: Downloading: /platform/tree/persons/LQRK-L93/notes.json
[2020-02-19 12:16:12]: Status code: 200
[2020-02-19 12:16:12]: Downloading: /service/tree/tree-data/reservations/person/
LQRK-L93/ordinances
[2020-02-19 12:16:13]: Status code: 200
[2020-02-19 12:16:13]: Downloading: /platform/tree/persons/LHT7-F2D/notes.json
[2020-02-19 12:16:13]: Status code: 204
[2020-02-19 12:16:13]: Downloading: /service/tree/tree-data/reservations/person/
LHT7-F2D/ordinances
[2020-02-19 12:16:13]: Status code: 200
[2020-02-19 12:16:13]: Downloading: /platform/tree/persons/K8F2-WVF/notes.json
[2020-02-19 12:16:13]: Status code: 200
[2020-02-19 12:16:13]: Downloading: /service/tree/tree-data/reservations/person/
K8F2-WVF/ordinances
[2020-02-19 12:16:13]: Status code: 204
[2020-02-19 12:16:13]: Downloading: /platform/tree/persons/KN7C-8YR/notes.json
[2020-02-19 12:16:13]: Status code: 200
[2020-02-19 12:16:13]: Downloading: /service/tree/tree-data/reservations/person/
KN7C-8YR/ordinances
[2020-02-19 12:16:14]: Status code: 200
[2020-02-19 12:16:14]: Downloading: /platform/tree/persons/KZ3B-9CF/notes.json
[2020-02-19 12:16:14]: Status code: 200
[2020-02-19 12:16:14]: Status code: 204
[2020-02-19 12:16:14]: Downloading: /service/tree/tree-data/reservations/person/
KZ3B-9CF/ordinances
[2020-02-19 12:16:14]: Downloading: /platform/tree/persons/KHSX-71K/notes.json
[2020-02-19 12:16:14]: Status code: 200
[2020-02-19 12:16:14]: Downloading: /service/tree/tree-data/reservations/person/
KHSX-71K/ordinances
[2020-02-19 12:16:14]: Status code: 200
[2020-02-19 12:16:14]: Downloading: /platform/tree/persons/L7K9-FV1/notes.json
[2020-02-19 12:16:14]: Status code: 200
[2020-02-19 12:16:14]: Downloading: /service/tree/tree-data/reservations/person/
L7K9-FV1/ordinances
[2020-02-19 12:16:15]: Status code: 204
[2020-02-19 12:16:15]: Downloading: /platform/tree/persons/K4TL-8YT/notes.json
[2020-02-19 12:16:15]: Status code: 204
[2020-02-19 12:16:15]: Downloading: /service/tree/tree-data/reservations/person/
K4TL-8YT/ordinances
[2020-02-19 12:16:15]: Status code: 200
[2020-02-19 12:16:15]: Downloading: /platform/tree/persons/KC9Q-C8P/notes.json
[2020-02-19 12:16:15]: Status code: 200
[2020-02-19 12:16:15]: Downloading: /service/tree/tree-data/reservations/person/
KC9Q-C8P/ordinances
[2020-02-19 12:16:15]: Status code: 200
[2020-02-19 12:16:15]: Downloading: /platform/tree/persons/L8PK-X8F/notes.json
[2020-02-19 12:16:15]: Status code: 200
[2020-02-19 12:16:15]: Downloading: /service/tree/tree-data/reservations/person/
L8PK-X8F/ordinances
[2020-02-19 12:16:16]: Status code: 204
[2020-02-19 12:16:16]: Downloading: /platform/tree/persons/K8B8-ZQL/notes.json
[2020-02-19 12:16:16]: Status code: 204
[2020-02-19 12:16:16]: Downloading: /service/tree/tree-data/reservations/person/
K8B8-ZQL/ordinances
[2020-02-19 12:16:16]: Status code: 200
[2020-02-19 12:16:16]: Status code: 200
[2020-02-19 12:16:16]: Downloading: /platform/tree/persons/K2TL-71X/notes.json
[2020-02-19 12:16:16]: Downloading: /service/tree/tree-data/reservations/person/
K2TL-71X/ordinances
[2020-02-19 12:16:16]: Status code: 200
[2020-02-19 12:16:16]: Downloading: /platform/tree/persons/J99X-KP4/notes.json
[2020-02-19 12:16:16]: Status code: 200
[2020-02-19 12:16:16]: Downloading: /service/tree/tree-data/reservations/person/
J99X-KP4/ordinances
[2020-02-19 12:16:17]: Status code: 200
[2020-02-19 12:16:17]: Downloading: /platform/tree/persons/9MBM-X4P/notes.json
[2020-02-19 12:16:17]: Status code: 204
[2020-02-19 12:16:17]: Downloading: /service/tree/tree-data/reservations/person/
9MBM-X4P/ordinances
[2020-02-19 12:16:17]: Status code: 204
[2020-02-19 12:16:17]: Downloading: /platform/tree/persons/KH9Y-33V/notes.json
[2020-02-19 12:16:17]: Status code: 204
[2020-02-19 12:16:17]: Downloading: /service/tree/tree-data/reservations/person/
KH9Y-33V/ordinances
[2020-02-19 12:16:17]: Status code: 200
[2020-02-19 12:16:17]: Downloading: /platform/tree/persons/LC3V-RKY/notes.json
[2020-02-19 12:16:18]: Status code: 200
[2020-02-19 12:16:18]: Downloading: /service/tree/tree-data/reservations/person/
LC3V-RKY/ordinances
[2020-02-19 12:16:18]: Status code: 204
[2020-02-19 12:16:18]: Downloading: /platform/tree/couple-relationships/MKSM-FMR
/notes.json
[2020-02-19 12:16:19]: Status code: 204
[2020-02-19 12:16:19]: Downloading: /platform/tree/couple-relationships/MJMT-KK9
/notes.json
[2020-02-19 12:16:19]: Status code: 200
[2020-02-19 12:16:19]: Downloading: /platform/tree/couple-relationships/MM1P-LZR
/notes.json
[2020-02-19 12:16:19]: Status code: 200
[2020-02-19 12:16:19]: Downloading: /platform/tree/couple-relationships/M3VJ-FF6
/notes.json
[2020-02-19 12:16:19]: Status code: 204
[2020-02-19 12:16:19]: Downloading: /platform/tree/couple-relationships/M9XW-CTT
/notes.json
[2020-02-19 12:16:19]: Status code: 200
[2020-02-19 12:16:19]: Downloading: /platform/tree/couple-relationships/MKHD-NTW
/notes.json
[2020-02-19 12:16:20]: Status code: 204
[2020-02-19 12:16:20]: Downloading: /platform/tree/couple-relationships/M4KL-9ZR
/notes.json
[2020-02-19 12:16:20]: Status code: 204
[2020-02-19 12:16:20]: Downloading: /platform/tree/couple-relationships/MPS1-DM6
/notes.json
[2020-02-19 12:16:20]: Status code: 204
[2020-02-19 12:16:20]: Downloading: /platform/tree/couple-relationships/M7ZJ-HFM
/notes.json
[2020-02-19 12:16:20]: Status code: 204
[2020-02-19 12:16:20]: Downloading: /platform/tree/couple-relationships/MJQS-WSB
/notes.json
[2020-02-19 12:16:20]: Status code: 200
[2020-02-19 12:16:20]: Downloading: /platform/tree/couple-relationships/MMZK-K9Z
/notes.json
[2020-02-19 12:16:20]: Status code: 204
[2020-02-19 12:16:20]: Downloading: /platform/tree/couple-relationships/M7ZN-XPR
/notes.json
[2020-02-19 12:16:21]: Status code: 204
[2020-02-19 12:16:21]: Downloading: /platform/tree/couple-relationships/MMX1-YLF
/notes.json
[2020-02-19 12:16:21]: Status code: 204
[2020-02-19 12:16:21]: Downloading: /platform/tree/couple-relationships/MVRL-WYW
/notes.json
[2020-02-19 12:16:21]: Status code: 204
[2020-02-19 12:16:21]: Downloading: /platform/tree/couple-relationships/MV7G-S33
/notes.json
[2020-02-19 12:16:21]: Status code: 204
[2020-02-19 12:16:21]: Downloading: /platform/tree/couple-relationships/M4KL-HXN
/notes.json
[2020-02-19 12:16:21]: Status code: 204
[2020-02-19 12:16:21]: Downloading: /platform/tree/couple-relationships/MN6C-D1B
/notes.json
[2020-02-19 12:16:21]: Status code: 204
[2020-02-19 12:16:21]: Downloading: /platform/tree/couple-relationships/M28S-H6Q
/notes.json
[2020-02-19 12:16:22]: Status code: 204
[2020-02-19 12:16:22]: Downloading: /platform/tree/couple-relationships/M4KL-92V
/notes.json
[2020-02-19 12:16:22]: Status code: 204
[2020-02-19 12:16:22]: Downloading: /platform/tree/couple-relationships/MHQR-KG4
/notes.json
[2020-02-19 12:16:22]: Status code: 204
[2020-02-19 12:16:22]: Status code: 204
[2020-02-19 12:16:22]: Status code: 204
[2020-02-19 12:16:22]: Status code: 204
[2020-02-19 12:16:23]: Status code: 204
[2020-02-19 12:16:23]: Status code: 204
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "fstogedcom.py", line 549, in download
    loop.run_until_complete(download_stuff(loop))
  File "C:\Python38\lib\asyncio\base_events.py", line 612, in run_until_complete

    return future.result()
  File "fstogedcom.py", line 540, in download_stuff
    await future
  File "C:\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "...\getmyancestors.py", line 1013, in add_
ordinances
    ret, famc = self.indi[fid].get_ordinances()
  File "...\getmyancestors\getmyancestors.py", line 637, in get_o
rdinances
    for key, o in data["data"].items():
AttributeError: 'NoneType' object has no attribute 'items'
`

**Comment by Linekio** [comment]
I couldn't reproduce the issue. 
It is possibly en temporary bug on the FamilySearch side.
Please try again and confirm here.

**Comment by Linekio** [comment]
Closes because no response for 1 month
