### ISSUE TITLE
Cannot run at all

### ISSUE THREAD

**Issue by marcusasplund** [Linekio/getmyancestors#44]
Steps to reproduce:
I tried to installl and run in 3 different env; mac, pc and linux and can't get it to run at all

Current behavior:

`$ python3 getmyancestors.py`

`Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "getmyancestors/__main__.py", line 1, in <module>
    from getmyancestors import getmyancestors
  File "getmyancestors/getmyancestors.py", line 14, in <module>
    from getmyancestors.classes.tree import Tree
ModuleNotFoundError: No module named 'getmyancestors.classes'; 'getmyancestors' is not a package`

Expected behavior:
To execute as expected

**Comment by Linekio** [comment]
Hello,
please try `python3 -m getmyancestors` or install executables with `pip install .`
